datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://pro-prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true

adminUser: admin
adminPassword: admin123!

service:
  type: LoadBalancer
  port: 1080
  targetPort: 3000
    # targetPort: 4181 To be used with a proxy extraContainer
  annotations: {}
  labels: {}
  portName: service

persistence:
  type: pvc
  enabled: enable
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
  # subPath: ""
  # existingClaim: